when@dev:
    zenstruck_foundry:
        faker:
            locale: fr_FR

when@test:
    zenstruck_foundry:
        faker:
            locale: fr_FR
        orm:
            reset:
                mode: !php/enum Zenstruck\Foundry\ORM\ResetDatabase\ResetDatabaseMode::MIGRATE
