<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260922101507 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Booking requests: workflow answers, private tracking token, calendar link; Messenger tables; Saturday arrival preference on rates';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        // Existing requests get a random token too, before the column becomes mandatory.
        $this->addSql('ALTER TABLE booking_request ADD tracking_token VARCHAR(48) DEFAULT NULL');
        $this->addSql('UPDATE booking_request SET tracking_token = md5(random()::text || id::text) || substr(md5(random()::text), 1, 16)');
        $this->addSql('ALTER TABLE booking_request ALTER tracking_token SET NOT NULL');
        $this->addSql('ALTER TABLE booking_request ADD agreed_price INT DEFAULT NULL');
        $this->addSql('ALTER TABLE booking_request ADD owner_message TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE booking_request ADD responded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE booking_request ADD outside_rules BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6129CABFB46BB896 ON booking_request (tracking_token)');
        $this->addSql('ALTER TABLE price_period ADD saturday_arrival BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE unavailability ADD booking_request_id UUID DEFAULT NULL');
        $this->addSql('ALTER TABLE unavailability ADD CONSTRAINT FK_F0016D1DBE4DBD4 FOREIGN KEY (booking_request_id) REFERENCES booking_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_F0016D1DBE4DBD4 ON unavailability (booking_request_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('DROP INDEX UNIQ_6129CABFB46BB896');
        $this->addSql('ALTER TABLE booking_request DROP tracking_token');
        $this->addSql('ALTER TABLE booking_request DROP agreed_price');
        $this->addSql('ALTER TABLE booking_request DROP owner_message');
        $this->addSql('ALTER TABLE booking_request DROP responded_at');
        $this->addSql('ALTER TABLE booking_request DROP outside_rules');
        $this->addSql('ALTER TABLE price_period DROP saturday_arrival');
        $this->addSql('ALTER TABLE unavailability DROP CONSTRAINT FK_F0016D1DBE4DBD4');
        $this->addSql('DROP INDEX IDX_F0016D1DBE4DBD4');
        $this->addSql('ALTER TABLE unavailability DROP booking_request_id');
    }
}
